version: "2"

services:
  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=md53175bce1d3201d16594cebf9d7eb3f9d
    volumes:
      - "hivems_dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=sa@broadsoftware.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    command: server /data


volumes:
  hivems_dbdata:
  minio_data:
  pgadmin_data:


